name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-dotnet@v4.3.1
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'source/Tubeshade.Server/package-lock.json'

      - name: Cache NuGet packages
        uses: actions/cache@v4.2.3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Run tests
        run: ./build/test.sh

      - name: Gather Code Coverage
        uses: codecov/codecov-action@v5.4.3
        if: false
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Gather Test Results
        uses: codecov/test-results-action@v1.1.1
        if: false
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  test-extension:
    name: Test browser extension
    runs-on: ubuntu-24.04
    container:
      image: mcr.microsoft.com/playwright:v1.54.1-noble
      options: --user 1001
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'extensions/browser/package-lock.json'

      - name: Run tests
        working-directory: './extensions/browser'
        run: |
          npm ci
          npm test

  build-debian-package:
    name: Build debian package
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-dotnet@v4.3.1
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'source/Tubeshade.Server/package-lock.json'

      - run: echo "BUILD_TAG=-test"

      - name: Cache NuGet packages
        uses: actions/cache@v4.2.3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Publish project
        id: publish
        run: build/publish.sh "Tubeshade.Server" "linux-x64" "${{ github.run_number }}" "-test"

      - name: Build debian package
        run: build/debian/debian.sh "${{ steps.publish.outputs.artifact }}" "${{ github.run_number }}"

      - uses: actions/upload-artifact@v4.6.2
        if: false
        with:
          name: Tubeshade.Server_linux-x64.deb
          path: "**/*.deb"
